# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BYZdt9g88wFD3226y-Gpi-3SM-nyvNJI
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

figsize=(6,4)
dpi=150

def f(x):
  return 2*x*x*np.cos(x)-5*x

fig,ax=plt.subplots(1,1,figsize=figsize,dpi=dpi)

t1=np.arange(-5.0,5.0,0.1)

ax.set_xlim(-5,5)
ax.set_ylim(-45,45)
ax.plot(t1,f(t1))

x=[-1]
y=[f(x[0])]

ax.plot(x,y,'ro')

print("X=",x)
print("Y=",y)

#la derivada de f(x) la pendiente

def df(x):
    return 4*x*np.cos(x)-2*x*x*np.sin(x)-5

pendiente=df(x[0])
print(pendiente)

eta=0.05
x.append(x[0]-eta*pendiente)
y.append(f(x[0]-eta*pendiente))
print("X:",x)
print("Y:",y)

ig,ax=plt.subplots(1,1,figsize=figsize,dpi=dpi)

t1=np.arange(-5.0,5.0,0.1)

ax.set_xlim(-5,5)
ax.set_ylim(-45,45)


ax.plot(t1,f(t1))
ax.plot(x,y,'ro')
